/// <reference types="Cypress"/>

describe("PUT/{id} successfully scenarios (Contract test)", () => {

    before(() => {
            cy.fixture('api/requestBodies/postBodyBefore.json').then((postBodyBefore) => {
            cy.log('Scenario to Create a device before the tests')
            cy.api({
                failOnStatusCode: false,
                method: 'POST',
                url: `${"/objects"}`,
                body: postBodyBefore
            }).then((response) => {
                expect(response.status).to.equal(200)
                Cypress.env('createdId', response.body.id)
            })
        })
    })

    it("Validate PUT with success using new post id", () => {
        const id = Cypress.env('createdId');
        cy.fixture('api/requestBodies/putBody.json').then((putBody) => {
            cy.log('Using the new device id to send a request to put')
            cy.api({
                failOnStatusCode: false,
                method: 'PUT',
                url: `${"/objects"}/${id}`,
                body: putBody
            }).then((response) => {
                const item = response.body;
                // validate status code
                expect(response.status).equal(200)

                // validate the id property and values
                expect(item).to.have.property('name', 'Apple MacBook Pro 16');
                expect(item.data).to.have.property('year', 2019);
                expect(item.data).to.have.property('price', 2049.99);
                expect(item.data).to.have.property('CPU model', 'Intel Core i9');
                expect(item.data).to.have.property('Hard disk size', '1 TB');
                expect(item.data).to.have.property('color', 'silver');
            })
        })
    })
})

describe("PUT/{id} alternative scenarios (Business Test)", () => {
    it("Validate PUT unauthorized for id 7", () => {
        cy.fixture('api/queryParams/getById.json').then((getById) => {
            const id = getById.id;
            cy.fixture('api/requestBodies/patchBody.json').then((patchBody) => {
                cy.log('Sending a request to PUT with id reserved = 7')
                cy.api({
                    failOnStatusCode: false,
                    method: 'PUT',
                    url: `${"/objects"}/${id}`,
                    body: patchBody
                }).then((response) => {
                    const item = response.body;

                    // validate status code
                    expect(response.status).equal(405)

                    // validate the error message from request 
                    expect(item).to.have.property("error", "7 is a reserved id and the data object of it cannot be overridden. You can create a new object via POST request and use new generated by id from it to send a PUT request.")
                })
            })
        })
    })

    it("Validate PUT with an invalid id", () => {
        cy.fixture('api/queryParams/invalidId.json').then((invalidId) => {
            const id = invalidId.id;
            cy.fixture('api/requestBodies/putBody.json').then((putBody) => {
                cy.log('Send an invalid id to PUT request')
                cy.api({
                    failOnStatusCode: false,
                    method: 'PUT',
                    url: `${"/objects"}/${id}`,
                    body: putBody
                }).then((response) => {
                    const item = response.body;
                    
                    // validate status code
                    expect(response.status).equal(404)

                    // validate the error message from request
                    expect(item).to.have.property("error", `The Object with id = ${id} doesn\'t exist. Please provide an object id which exists or generate a new Object using POST request and capture the id of it to use it as part of PUT request after that.`)
                })
            })
        })
    })
})
